# Generated by Django 4.0.3 on 2022-03-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='cT',
        ),
        migrations.RemoveField(
            model_name='process',
            name='tAT',
        ),
        migrations.RemoveField(
            model_name='process',
            name='wT',
        ),
    ]
