# Generated by Django 4.0.3 on 2022-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_process_ct_remove_process_tat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cT', models.IntegerField()),
                ('tAT', models.IntegerField()),
                ('wT', models.IntegerField()),
            ],
        ),
    ]
