# Generated by Django 4.0.3 on 2022-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cal_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_p', models.IntegerField()),
            ],
        ),
    ]
