# Generated by Django 4.0.3 on 2022-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cal_process_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='pID',
            field=models.IntegerField(unique=True),
        ),
    ]
