# Generated by Django 4.0.3 on 2022-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_process_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='avg_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_proc_wt', models.FloatField()),
                ('avg_proc_tat', models.FloatField()),
            ],
        ),
    ]
