# Generated by Django 4.0.3 on 2022-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.IntegerField()),
                ('aT', models.IntegerField()),
                ('bT', models.IntegerField()),
                ('cT', models.IntegerField()),
                ('tAT', models.IntegerField()),
                ('wT', models.IntegerField()),
            ],
        ),
    ]
